[{'secure': False, 'name': '_T_WM', 'path': '/', 'httpOnly': True, 'expiry': 1504968712.142471, 'domain': '.weibo.cn', 'value': 'f938d614bb97f53e526d28f38e3fd800'}]
 (￣y▽￣)╭可能登录失败了手动登录一下吧
判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-1")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-2")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-3")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-4")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-5")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-6")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-7")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-8")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-9")>, <selenium.webdriver.remote.webelement.WebElement (session="d4f9da758204b30880323e8dc23a4b19", element="0.1727761961725669-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-10 22:52:28
1
False
2
False
3
False
4
False
5
False
6
False
7
False
8
False
9
False
10
False
11
False
12
False
13
False
14
False
15
False
16
False
17
False
18
False
19
False
20
False
21
False
22
False
23
False
24
False
25
False
26
False
27
False
28
False
29
False
30
False
31
False
Traceback (most recent call last):
  File "my_repost.py", line 192, in <module>
    repost(driver1)
  File "my_repost.py", line 161, in repost
    browser.find_element_by_tag_name('body').send_keys(Keys.CONTROL + 'w')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 707, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 693, in create_connection
    sock = socket(af, socktype, proto)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 23] Too many open files in system
