判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-1")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-2")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-3")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-4")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-5")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-6")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-7")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-8")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-9")>, <selenium.webdriver.remote.webelement.WebElement (session="9aeebcbd35f490f6e3e3b2db39f75901", element="0.5114171622635699-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 01:34:56
Traceback (most recent call last):
  File "test_repost_new.py", line 250, in <module>
    #        print('33333333')
  File "test_repost_new.py", line 219, in repost
    send = browser.find_element_by_class_name('m-send-btn')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 707, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 693, in create_connection
    sock = socket(af, socktype, proto)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 23] Too many open files in system
