判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-1")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-2")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-3")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-4")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-5")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-6")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-7")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-8")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-9")>, <selenium.webdriver.remote.webelement.WebElement (session="428a9829043af3bb55731c8d77c0e277", element="0.7574873991235365-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 01:40:22
Traceback (most recent call last):
  File "test_repost_new.py", line 250, in <module>
    #        print('33333333')
  File "test_repost_new.py", line 221, in repost
    sleep(10)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/support/expected_conditions.py", line 339, in __call__
    alert.text
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/common/alert.py", line 69, in text
    return self.driver.execute(Command.GET_ALERT_TEXT)["value"]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/remote_connection.py", line 487, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 707, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 693, in create_connection
    sock = socket(af, socktype, proto)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 23] Too many open files in system
