判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-1")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-2")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-3")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-4")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-5")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-6")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-7")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-8")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-9")>, <selenium.webdriver.remote.webelement.WebElement (session="c3c90e53a98fa0859766f4dc2738fba8", element="0.021365312940767378-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 01:41:52
Traceback (most recent call last):
  File "test_repost_new.py", line 250, in <module>
    #        print('33333333')
  File "test_repost_new.py", line 209, in repost
    browser.find_element_by_tag_name('body').send_keys(Keys.CONTROL + 't')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)

