[{'name': '_T_WM', 'httpOnly': True, 'domain': '.weibo.cn', 'path': '/', 'expiry': 1504618404.529, 'value': 'bd8f3ab1a2062c2a6f5ed674888f015a', 'secure': False}]
 (￣y▽￣)╭可能登录失败了手动登录一下吧
判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-1")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-2")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-3")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-4")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-5")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-6")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-7")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-8")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-9")>, <selenium.webdriver.remote.webelement.WebElement (session="5457229a38757786a031f0357847f644", element="0.7478399640276356-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 21:33:59
1
False
2
False
3
False
4
False
5
False
6
False
7
False
8
False
9
False
10
False
11
False
12
False
Traceback (most recent call last):
  File "my_repost.py", line 188, in <module>
    try:
  File "my_repost.py", line 157, in repost
    sleep(10)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)

