[{'secure': False, 'domain': '.weibo.cn', 'value': '720b8246693f87cddb7d54a001bb8ebb', 'expiry': 1504618224.564346, 'path': '/', 'httpOnly': True, 'name': '_T_WM'}]
 (￣y▽￣)╭可能登录失败了手动登录一下吧
判断页面1成功 0失败  结果是=1
伦哥：呜呜呜，13175170469----abc12345 这个号不能用啦 
Traceback (most recent call last):
  File "my_repost.py", line 185, in <module>
    elems1 = handleLogin(driver1, usrname, pwd)
  File "my_repost.py", line 95, in handleLogin
    brower.close()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 541, in close
    self.execute(Command.CLOSE)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)

