 (￣y▽￣)╭可能登录失败了手动登录一下吧
判断页面1成功 0失败  结果是=1
[<selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-1")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-2")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-3")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-4")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-5")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-6")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-7")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-8")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-9")>, <selenium.webdriver.remote.webelement.WebElement (session="b59b9c37c966672f608ed8046e9060d1", element="0.49379228081498927-10")>]
伦哥：好棒！第1次运行了
运行时间：2017-08-06 00:55:21
Traceback (most recent call last):
  File "test_repost_new.py", line 245, in <module>
    cookie3 = driver1.get_cookies()
  File "test_repost_new.py", line 204, in repost
    for id in idSet:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 409, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"textarea"}
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.6 x86_64)

